version: "3.7"
services:
  api:
    build:
      context: ./src/server
    depends_on:
      - postgres
    volumes:
      - .env:/go/src/app/.env
      - ./public-firebase-config.json:/go/src/app/public-firebase-config.json
      - ./service-account-file.json:/go/src/app/service-account-file.json
    restart: unless-stopped
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    restart: unless-stopped
volumes:
  postgres:
